# $FreeBSD$

PORTNAME=	osc
PORTVERSION=	0.2
CATEGORIES=	audio
MASTER_SITES=	http://puredata.info/downloads/${PORTNAME}/${PORTVERSION}/
PKGNAMEPREFIX=	pd-

MAINTAINER=	brittlehaus@gmail.com
COMMENT=	Collection of Pd objectclasses for OSC-messages

LICENSE=	GPLv2+

BUILD_DEPENDS=	pd:${PORTSDIR}/audio/pd
RUN_DEPENDS=	pd:${PORTSDIR}/audio/pd

USES=		gmake

.include <bsd.port.mk>
