# $FreeBSD$

PORTNAME=	maxlib
PORTVERSION=	1.5.5
CATEGORIES=	audio
MASTER_SITES=	http://sourceforge.net/projects/pure-data/files/libraries/${PORTNAME}/
PKGNAMEPREFIX=	pd-

MAINTAINER=	brittlehaus@gmail.com
COMMENT=	Library of non-tilde objects for Pd

LICENSE=	GPLv2

BUILD_DEPENDS=	pd:${PORTSDIR}/audio/pd
RUN_DEPENDS=	pd:${PORTSDIR}/audio/pd

USES=		gmake

.include <bsd.port.mk>
